In [2]:
import numpy as np
import matplotlib.pylab as plt
import pandas as pd

In [3]:
print(pd.__version__)

3.0.5

In [6]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df = pd.read_csv(url)
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
df.shape

(10000, 11)

In [8]:
df["fuel_type"].nunique()

3

In [9]:
df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [10]:
df.isnull().any().sum()

np.int64(2)

In [11]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [13]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [14]:
df["horsepower"].median()

np.float64(254.0)

In [21]:
mostfrequent=df["horsepower"].mode()[0]

In [22]:
df["horsepower"] = df["horsepower"].fillna(mostfrequent)

In [23]:
df["horsepower"].median()

np.float64(252.0)

In [25]:
df_asia=df[df["origin"] == "Asia"]
df_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [29]:
df_asia = df_asia[["vehicle_weight", "model_year"]]
df_asia.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [32]:
x=df_asia.iloc[:7].to_numpy()
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [34]:
xtx=np.dot(x.T, x)
xtx

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [36]:
xtx_inv=np.linalg.inv(xtx)
xtx_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [37]:
y=[1100, 1300, 800, 900, 1000, 1100, 1200]

In [41]:
w=np.dot(np.dot(xtx_inv, x.T),y)
w

array([0.13644777, 0.2327492 ])

In [42]:
w.sum()

np.float64(0.36919696904925486)